"""In-memory thread-safe artifact registry and safe artifact resolution."""

from __future__ import annotations

import logging
import os
import threading
import time
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import ClassVar

from meter_reading_engine.contracts import ArtifactIndex, ArtifactRole

from meter_reading_inference_service.errors import ArtifactNotFoundError

logger = logging.getLogger(__name__)

ALLOWED_PUBLIC_ROLES: set[str] = {
    "source",
    "display",
    "working_display",
    "reading_value",
}

ROLE_MIME_TYPES: dict[str, str] = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
}


@dataclass(frozen=True)
class RegisteredRunArtifacts:
    run_id: str
    created_at_epoch: float
    role_to_path: dict[str, Path]
    media_types: dict[str, str]


class InMemoryArtifactRegistry:
    """Thread-safe LRU/TTL in-memory registry for run artifact paths."""

    ROLE_MAP: ClassVar[dict[str, ArtifactRole]] = {
        "source": ArtifactRole.SOURCE,
        "display": ArtifactRole.DISPLAY,
        "working_display": ArtifactRole.WORKING_DISPLAY,
        "reading_value": ArtifactRole.READING_VALUE,
    }

    def __init__(
        self,
        artifact_root: Path,
        capacity: int = 256,
        ttl_seconds: int = 86400,
    ) -> None:
        self.artifact_root = artifact_root.resolve()
        self.capacity = max(1, capacity)
        self.ttl_seconds = max(1, ttl_seconds)
        self._entries: OrderedDict[str, RegisteredRunArtifacts] = OrderedDict()
        self._lock = threading.Lock()

    def register_index(self, run_id: str, artifact_index: ArtifactIndex) -> None:
        """Register the artifact index generated by Core pipeline for a run."""
        now = time.time()
        role_to_path: dict[str, Path] = {}
        media_types: dict[str, str] = {}

        # Resolve paths relative to artifact_root / run_relative_root
        base_dir = (self.artifact_root / artifact_index.run_relative_root).resolve()

        for art_ref in artifact_index.artifacts:
            role_str = (
                art_ref.role.value.lower()
                if hasattr(art_ref.role, "value")
                else str(art_ref.role).lower()
            )
            if role_str in ALLOWED_PUBLIC_ROLES:
                art_file = (base_dir / art_ref.relative_path).resolve()
                role_to_path[role_str] = art_file
                media_types[role_str] = art_ref.media_type or "image/jpeg"

        with self._lock:
            # Evict expired
            self._evict_expired_locked(now)

            # Evict LRU if at capacity
            if len(self._entries) >= self.capacity:
                self._entries.popitem(last=False)

            self._entries[run_id] = RegisteredRunArtifacts(
                run_id=run_id,
                created_at_epoch=now,
                role_to_path=role_to_path,
                media_types=media_types,
            )

    def register_direct(
        self,
        run_id: str,
        role_to_path: dict[str, Path],
        media_types: dict[str, str] | None = None,
    ) -> None:
        """Direct registration helper for testing or synthetic runs."""
        now = time.time()
        with self._lock:
            self._evict_expired_locked(now)
            if len(self._entries) >= self.capacity:
                self._entries.popitem(last=False)
            self._entries[run_id] = RegisteredRunArtifacts(
                run_id=run_id,
                created_at_epoch=now,
                role_to_path={k.lower(): v.resolve() for k, v in role_to_path.items()},
                media_types=media_types or {},
            )

    def resolve_artifact_file(self, run_id: str, role: str) -> tuple[Path, str]:
        """Safely resolve an artifact path and media type, guarding against traversal."""
        role_key = role.lower().strip()
        if role_key not in ALLOWED_PUBLIC_ROLES:
            raise ArtifactNotFoundError(message=f"Unknown or disallowed artifact role '{role}'")

        now = time.time()
        with self._lock:
            entry = self._entries.get(run_id)
            if entry is None:
                raise ArtifactNotFoundError(message=f"No artifacts found for run_id '{run_id}'")

            # Check expiry
            if now - entry.created_at_epoch > self.ttl_seconds:
                self._entries.pop(run_id, None)
                raise ArtifactNotFoundError(
                    message=f"Artifact record expired for run_id '{run_id}'"
                )

            # Touch for LRU
            self._entries.move_to_end(run_id)
            file_path = entry.role_to_path.get(role_key)
            declared_media_type = entry.media_types.get(role_key)

        if file_path is None:
            raise ArtifactNotFoundError(
                message=f"Role '{role_key}' not present for run_id '{run_id}'"
            )

        # Security check: Canonical containment under configured artifact_root
        try:
            resolved_file = file_path.resolve()
            resolved_root = self.artifact_root.resolve()

            # Check if resolved_file is strictly inside resolved_root or within temp storage
            # os.path.commonpath ensures no path traversal escape
            common = Path(os.path.commonpath([str(resolved_file), str(resolved_root)]))
            if common != resolved_root:
                logger.warning(
                    "Path traversal attempt detected: file %s outside root %s",
                    resolved_file,
                    resolved_root,
                )
                raise ArtifactNotFoundError(message="Artifact not found")

        except Exception as e:
            if isinstance(e, ArtifactNotFoundError):
                raise
            raise ArtifactNotFoundError(message="Artifact not found") from e

        if not resolved_file.is_file():
            raise ArtifactNotFoundError(message=f"Artifact file missing for run_id '{run_id}'")

        # Determine MIME
        media_type = declared_media_type
        if not media_type:
            suffix = resolved_file.suffix.lower()
            media_type = ROLE_MIME_TYPES.get(suffix, "image/jpeg")

        return resolved_file, media_type

    def get_available_roles(self, run_id: str) -> list[str]:
        """Return list of available roles for a registered run."""
        with self._lock:
            entry = self._entries.get(run_id)
            if not entry:
                return []
            return list(entry.role_to_path.keys())

    def _evict_expired_locked(self, now: float) -> None:
        """Evict records older than ttl_seconds. Must be called while holding self._lock."""
        expired_keys = [
            k
            for k, entry in self._entries.items()
            if (now - entry.created_at_epoch) > self.ttl_seconds
        ]
        for k in expired_keys:
            self._entries.pop(k, None)
